[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'tomasr/molokai'
hook_add = '''
augroup SetColorScheme 
    au!
    au VimEnter * nested colorscheme molokai
augroup END
    '''

[[plugins]]
repo = 'Townk/vim-autoclose'

[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'scrooloose/nerdcommenter'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = 'python'

[[plugins]]
repo = "nvie/vim-flake8"
on_ft = 'python'
